### ISSUE TITLE
HFD801KJC Identification

### ISSUE THREAD

**Issue by gmallios** [SonixQMK/Mechanical-Keyboard-Database#45]
The HFD801KJC IC used in the GMK67 (and others) could benefit heavily by porting QMK to it.
How do you identify which is the rebranded Sonix chip?
Also, the docs could benefit with instructions on how to dump the FW.

**Comment by dexter93** [comment]
HFD801KJC is a clone/rebrand of [WCH CH555](https://www.wch-ic.com/products/CH555.html) and not a Sonix chip. There seems to be an attempt for QMK on it [here](https://github.com/vuhuycan/qmk-8051)
